# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: python

sudo: required

services:
  - docker

env: SH="docker exec -t ubuntu-test bash -c"

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis -w /travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - $SH "apt-get update"
  - $SH "apt-get install -y software-properties-common python python3 python3-pip"
  - $SH "python3 -m pip install -q --upgrade pip"
  - $SH "python3 -m pip install -q tox"
  - $SH "add-apt-repository ppa:deadsnakes/ppa"
  - $SH "apt-get update"
  - $SH "apt-get install -y python2.6 python3.4 python3.5 python3.7"

script:
  - $SH "tox"

notifications:
    email: false
